#!/usr/bin/env bash
vmConf="${HOME}/Parallels/macOS.macvm/config.ini"
res=$(system_profiler SPDisplaysDataType | grep -wo "Resolution:.*")
disWidth=$(echo $res | awk '{print $2}')
disHeight=$(echo $res | awk '{print $4}')

sed -i '' "s/DisplayWidth=.*/DisplayWidth=$disWidth/g" $vmConf
sed -i '' "s/DisplayHeight=.*/DisplayHeight=$disHeight/g" $vmConf

"/Applications/Parallels Desktop.app/Contents/MacOS/Parallels Mac VM.app/Contents/MacOS/prl_macvm_app" \
--openvm /Users/anthony/Parallels/macOS.macvm \
--log-dir /Users/anthony/Parallels/macOS.macvm